
module.exports = {
  "/v1/admin/brand": ["/brand-list", "/item-list"],
  "/v1/admin/marketers": ["/marketer-list", "/item-list"],
  "/v1/admin/product_class": "/product-class-list",
  "/v1/admin/product_category": "/product-category-list",
  "/v1/admin/product_sub_category": "/product-sub-category-list",
  "/v1/admin/category": "/business-segment-list",
  "/v1/admin/country": "/country-list",
  "/v1/admin/units": "/unit-list",
  "/v1/admin/state": "/state-list",
  "/v1/admin/district": "/district-list",
  "/v1/admin/tehsil": "/tehsil-list",
  "/v1/admin/pin": "/pin-list",
  "/v1/admin/place": "/Place-list",
  "/v1/admin/product": "/item-list",
  "/v1/admin/business_entity_basic/gstpan": "/business-entity-list",
  "/v1/admin/business_entity_basic": "/business-entity-list",
  "/v1/admin/business_bank_details": "/business-entity-list",
  "/v1/admin/be_gst_details": "/business-entity-list",
  "/v1/admin/business_area_information": "/business-entity-list",
  "/v1/admin/Business_warehouse_information": "/warehouse-list",
  "/v1/admin/Business_license_details": "",
  "/v1/admin/Business_owner_details": "/business-entity-list",
  "/v1/admin/staff": "/staff-list",
  "/v1/admin/supplier": "/supplier-type-list",
  "/v1/admin/sub_category": "/business-sub-category-list",
  "/v1/admin/gst_percent": "/gst-list",
  "/v1/admin/vender_lead": "/vendor-lead-list",
  "/v1/admin/customer_lead": "/customer-lead-list",
  "/v1/admin/product_child_category": "/product-child-category-list",
  "/v1/admin/license_category": "/license-category-list",
  "/v1/admin/master_product": ["/product-list", , "/item-list"],
  "/v1/admin/be_document": "/business-entity-list",
  "/v1/admin/product_area": "/product-area-list",
  "/v1/admin/business_area_teritari": "/territory-list",
  "/v1/admin/business_area": "/area-list",
  "/v1/admin/business_area_region": "/region-list",
  "/v1/admin/business_area_zone": "/zone-list",
  "/v1/admin/lead_category": "/lead-category-list",
  "/v1/admin/lead_sub_category": "/lead-subcategory-list",
  "/v1/admin/license": "/license-list",
  "/v1/admin/vender_category": "/vendor-category-list",
  "/v1/admin/customer_category": "/customer-category-list",
  "/v1/admin/license_product": "/license-list",
  "/v1/admin/menu_plan": "/roles-list",
  "/v1/admin/productcatalogue": "",
  "/v1/admin/rake": "/rack-list",
  "/v1/admin/logistic_area": "/logistic-area-list",
  "/v1/admin/shiptoparty": "/ship-to-party-list",
  "/v1/admin/item_variants": "/variant-list",

  "/v1/admin/be_vendor": "/vendor-list",
  "/v1/admin/be_customer": "/customer-list",
  "/v1/admin/vendor_business_bank_details": "/vendor-list",
  "/v1/admin/customer_business_bank_details": "/customer-list",
  "/v1/admin/vendor_be_document": "/vendor-list",
  "/v1/admin/customer_be_document": "/customer-list",
  "/v1/admin/vendor_be_gst_details": "/vendor-list",
  "/v1/admin/customer_be_gst_details": "/customer-list",
  "/v1/admin/vendor_license_details": "/vendor-list",
  "/v1/admin/vendor_warehouse_details": "/vendor-list",




  // "/v1/admin/auth/marketers": "/item-list",
  // "/v1/admin/auth/brand": "/item-list",
  // "/v1/admin/auth/master_product": "/item-list",



  "/v1/admin/o_form_versioning": "/oform-versioning-list",
  "/v1/admin/o_form_issue": "/oform-list",
  "/v1/admin/order_so_po": "/sales-order-list",
  "/v1/admin/order_payments": "/payment",
  "/v1/admin/order_activity": "/activity",



};