# Use Node.js base image
FROM node:17

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Copy the .env file into the image
COPY .env .env

# Expose the application port
EXPOSE 3005

# Start the application in development mode
CMD ["npm", "run", "start:dev"]
