# Use a minimal Node.js base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy only package files first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy rest of the source code
COPY . .

# Expose the app port
EXPOSE 3005

# Run the app
CMD ["npm", "run", "start:dev"]
