import React from "react";

const planData = [
  {
    id: 1,
    name: "Basic Plan",
    features: [
      {
        name: "Course & Batch Management",
        quarterly: true,
        halfYearly: true,
        yearly: true,
      },
      {
        name: "Teacher & Learner Management",
        quarterly: true,
        halfYearly: true,
        yearly: true,
      },
      {
        name: "Learner Portal Access",
        quarterly: true,
        halfYearly: true,
        yearly: true,
      },
      {
        name: "Teacher Portal Access",
        quarterly: true,
        halfYearly: true,
        yearly: true,
      },
      {
        name: "Interactive Notes",
        quarterly: true,
        halfYearly: true,
        yearly: true,
      },
      {
        name: "Digital eBooks",
        quarterly: true,
        halfYearly: true,
        yearly: true,
      },
      {
        name: "Streaming Video Content",
        quarterly: "GD & YT",
        halfYearly: "GD & YT",
        yearly: "GD N YT AND CLOUD 5 GB",
      },
      {
        name: "Content Publishing Suite",
        quarterly: true,
        halfYearly: true,
        yearly: true,
      },
      {
        name: "Bookstore Platform",
        quarterly: true,
        halfYearly: true,
        yearly: true,
      },
      {
        name: "Scheduling & Timetable",
        quarterly: true,
        halfYearly: true,
        yearly: true,
      },
      {
        name: "Interactive Doubt Resolution",
        quarterly: false,
        halfYearly: false,
        yearly: "3 month Trial",
      },
      {
        name: "Feedback & Review System",
        quarterly: false,
        halfYearly: false,
        yearly: "3 month Trial",
      },
      {
        name: "Live Virtual Classroom",
        quarterly: false,
        halfYearly: false,
        yearly: false,
      },
      {
        name: "Assessment & Test Series",
        quarterly: false,
        halfYearly: false,
        yearly: false,
      },
      {
        name: "SMS Notifications",
        quarterly: false,
        halfYearly: false,
        yearly: false,
      },
      {
        name: "Email Communication",
        quarterly: false,
        halfYearly: false,
        yearly: false,
      },
      {
        name: "Telecommunication Support",
        quarterly: false,
        halfYearly: false,
        yearly: false,
      },
      {
        name: "Dynamic Forms",
        quarterly: false,
        halfYearly: false,
        yearly: false,
      },
      {
        name: "Examination Suite",
        quarterly: false,
        halfYearly: false,
        yearly: false,
      },
      {
        name: "Mobile Learning App",
        quarterly: false,
        halfYearly: false,
        yearly: false,
      },
      {
        name: "Rapid Access Website",
        quarterly: false,
        halfYearly: false,
        yearly: false,
      },
    ],
    prices: {
      quarterly: 3000,
      halfYearly: 6000,
      yearly: 10200,
    },
  },
  {
    id: 2,
    name: "Standard Plan",
    features: [
        {
          name: "Course & Batch Management",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Teacher & Learner Management",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Learner Portal Access",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Teacher Portal Access",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Interactive Notes",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Digital eBooks",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Streaming Video Content",
          quarterly: "GD N YT AND CLOUD 5 GB",
          halfYearly: "GD N YT AND CLOUD 5 GB",
          yearly: "GD N YT AND CLOUD 10 GB",
        },
        {
          name: "Content Publishing Suite",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Bookstore Platform",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Scheduling & Timetable",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Interactive Doubt Resolution",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Feedback & Review System",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Live Virtual Classroom",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Assessment & Test Series",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "SMS Notifications",
          quarterly: false,
          halfYearly: false,
          yearly: true,
        },
        {
          name: "Email Communication",
          quarterly: false,
          halfYearly: false,
          yearly: true,
        },
        {
          name: "Telecommunication Support",
          quarterly: false,
          halfYearly: false,
          yearly: true,
        },
        {
          name: "Dynamic Forms",
          quarterly: false,
          halfYearly: false,
          yearly: true,
        },
        {
          name: "Examination Suite",
          quarterly: false,
          halfYearly: false,
          yearly: "1 month Trial",
        },
        {
          name: "Mobile Learning App",
          quarterly: false,
          halfYearly: false,
          yearly: false,
        },
        {
          name: "Rapid Access Website",
          quarterly: false,
          halfYearly: false,
          yearly: false,
        },
      ],
    prices: {
      quarterly: 4500,
      halfYearly: 9000,
      yearly: 25200,
    },
  },
  {
    id: 3,
    name: "Premium Plan",
    features: [
        {
          name: "Course & Batch Management",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Teacher & Learner Management",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Learner Portal Access",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Teacher Portal Access",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Interactive Notes",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Digital eBooks",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Streaming Video Content",
          quarterly: "GD N YT AND CLOUD 5 GB",
          halfYearly: "GD N YT AND CLOUD 20 GB",
          yearly: "GD N YT AND CLOUD 20 GB",
        },
        {
          name: "Content Publishing Suite",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Bookstore Platform",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Scheduling & Timetable",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Interactive Doubt Resolution",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Feedback & Review System",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Live Virtual Classroom",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Assessment & Test Series",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "SMS Notifications",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Email Communication",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Telecommunication Support",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Dynamic Forms",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Examination Suite",
          quarterly: "with 100 Users",
          halfYearly: "with 100 Users",
          yearly: "with 100 Users",
        },
        {
          name: "Mobile Learning App",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
        {
          name: "Rapid Access Website",
          quarterly: true,
          halfYearly: true,
          yearly: true,
        },
      ],
    prices: {
      quarterly: 25500,
      halfYearly: 51000,
      yearly: 100200,
    },
  },
];

export default planData;
