const moment = require('moment');
exports.seed = async function (knex) {
  console.log('Seeding Integrated_modules_sub_menu table...');
  const IntegratedModulesSubMenuRecords = [
    {
      id: 1,
      index_id: 1,
      main_menu_id: 2, // Ensure this exists in `Integrated_modules_main_menu`
      name: 'Buisness',
      type: 'dropdown',
      icon: 'Buisness',
      path: '/buisness',
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment().toISOString(),
      updated_at: moment().toISOString(),
    },
    {
      id: 2,
      index_id: 2,
      name: 'Product',
      type: 'dropdown',
      icon: 'Product',
      path: '/product',
      main_menu_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 3,
      index_id: 3,
      name: 'Demographics',
      type: 'dropdown',
      icon: 'Demographics',
      path: '/demographics',
      main_menu_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 4,
      index_id: 1,
      name: 'Business Entity',
      type: 'link',
      icon: 'Business Entity',
      path: '/business-entity-list',
      main_menu_id: 3,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 5,
      index_id: 2,
      name: 'Lending Partner',
      type: 'link',
      icon: 'Lending Partner',
      path: '/lending-list',
      main_menu_id: 3,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 6,
      index_id: 3,
      name: 'Logistics Partner',
      type: 'link',
      icon: 'Logistics',
      path: '/logistics-list',
      main_menu_id: 3,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 7,
      index_id: 1,
      name: 'Book a demo',
      type: 'link',
      icon: 'Book a demo',
      path: '/book-a-demo-list',
      main_menu_id: 4,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 8,
      index_id: 2,
      name: 'Contact Us',
      type: 'link',
      icon: 'Contact Us',
      path: '/contact-list',
      main_menu_id: 4,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 9,
      index_id: 1,
      name: 'Text Sms',
      type: 'link',
      icon: 'Text Sms',
      path: '/text-sms-list',
      main_menu_id: 9,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 10,
      index_id: 2,
      name: 'WhatsApp ',
      type: 'link',
      icon: 'WhatsApp',
      path: '/whatsapp-list',
      main_menu_id: 9,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 11,
      index_id: 3,
      name: 'Email',
      type: 'link',
      icon: 'Email',
      path: '/email-list',
      main_menu_id: 9,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 12,
      index_id: 4,
      name: 'Agriza Forms',
      type: 'link',
      icon: 'Agriza Forms',
      path: '/agriza-form-list',
      main_menu_id: 9,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 13,
      index_id: 1,
      name: 'Product Catalogue',
      type: 'link',
      icon: 'Product Catalogue',
      path: '/product-catalogue-list',
      main_menu_id: 15,
      active_status: 'inactive',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 14,
      index_id: 2,
      name: 'Product Bucket',
      type: 'link',
      icon: 'Product Bucket',
      path: '/product-bucket-list',
      main_menu_id: 15,
      active_status: 'inactive',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 15,
      index_id: 3,
      name: 'Request new Product',
      type: 'link',
      icon: 'Request new Product',
      path: '/item-list',
      main_menu_id: 15,
      active_status: 'inactive',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 16,
      index_id: 4,
      name: 'Price Update',
      type: 'link',
      icon: 'Price update',
      path: '/price-update-list',
      main_menu_id: 15,
      active_status: 'inactive',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 17,
      index_id: 1,
      name: 'Vendor lead',
      type: 'link',
      icon: 'Vendor Lead',
      path: '/vendor-lead-list',
      main_menu_id: 16,
      active_status: 'inactive',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 18,
      index_id: 2,
      name: 'Customer lead',
      type: 'link',
      icon: 'Customer Lead',
      path: '/customer-lead-list',
      main_menu_id: 16,
      active_status: 'inactive',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 19,
      index_id: 1,
      name: 'Purchase Order',
      type: 'link',
      icon: 'Purchase Order',
      path: '/purchase-order-list',
      main_menu_id: 19,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 20,
      index_id: 1,
      name: 'Sales Order',
      type: 'link',
      icon: 'Sales Order',
      path: '/sales-order-list',
      main_menu_id: 19,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 21,
      index_id: 1,
      name: 'Marketing',
      type: 'link',
      icon: 'Marketing',
      path: '/marketing-setting',
      main_menu_id: 25,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 22,
      index_id: 1,
      name: 'Marketing',
      type: 'link',
      icon: 'Marketing',
      path: '/marketing-setting',
      main_menu_id: 10,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 23,
      index_id: 1,
      name: 'Text Sms',
      type: 'link',
      icon: 'Text Sms',
      path: '/text-sms-list',
      main_menu_id: 24,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 24,
      index_id: 2,
      name: 'WhatsApp ',
      type: 'link',
      icon: 'WhatsApp',
      path: '/whatsapp-list',
      main_menu_id: 24,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 25,
      index_id: 3,
      name: 'Email',
      type: 'link',
      icon: 'Email',
      path: '/email-list',
      main_menu_id: 24,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 26,
      index_id: 4,
      name: 'Agriza Forms',
      type: 'link',
      icon: 'Agriza Forms',
      path: '/agriza-form-list',
      main_menu_id: 24,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 27,
      index_id: 2,
      name: 'BE Users',
      type: 'link',
      icon: 'BE Users',
      path: '/be-users-list',
      main_menu_id: 5,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 28,
      index_id: 3,
      name: 'NBFC Applied list',
      type: 'link',
      icon: 'NBFC Applied list',
      path: '/nbfc-applied-list',
      main_menu_id: 5,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 29,
      index_id: 4,
      name: 'Logistic Applied list',
      type: 'link',
      icon: 'Logistic Applied list',
      path: '/logistics-applied-list',
      main_menu_id: 5,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 30,
      index_id: 1,
      name: 'Agriza Buyers',
      type: 'link',
      icon: 'Agriza Buyers',
      path: '/agriza-buyer-list',
      main_menu_id: 5,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 31,
      index_id: 1,
      name: 'Roles & Responsibility',
      type: 'link',
      icon: 'Roels & Responsibility',
      path: '/roles-list',
      main_menu_id: 11,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 32,
      index_id: 2,
      name: 'Office Staff',
      type: 'link',
      icon: 'office Staff',
      path: '/staff-list',
      main_menu_id: 11,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 33,
      index_id: 4,
      name: 'Business Area',
      type: 'dropdown',
      icon: 'Business Area',
      path: '/business-area-list',
      main_menu_id: 14,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 34,
      index_id: 1,
      name: 'Warehouse',
      type: 'dropdown',
      icon: 'Warehouse',
      path: '/warehouse-list',
      main_menu_id: 14,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 35,
      index_id: 2,
      name: 'License',
      type: 'dropdown',
      icon: 'License',
      path: '/license-list',
      main_menu_id: 14,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 36,
      index_id: 1,
      name: 'Staff',
      type: 'link',
      icon: 'Staff',
      path: '/staff-list',
      main_menu_id: 26,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 37,
      index_id: 2,
      name: 'Roles & Responsiblity',
      type: 'link',
      icon: 'Roles & Responsiblity',
      path: '/roles-list',
      main_menu_id: 26,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 38,
      index_id: 2,
      name: 'Item Area',
      type: 'link',
      icon: 'Item Area',
      path: '/product-area-list',
      main_menu_id: 14,
      active_status: 'inactive',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 39,
      index_id: 6,
      name: 'Lead',
      type: 'dropdown',
      icon: 'lead',
      path: '/lead',
      main_menu_id: 14,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 40,
      index_id: 7,
      name: 'Vendor Category',
      type: 'link',
      icon: 'vendor Category',
      path: '/vendor-category-list',
      main_menu_id: 14,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 41,
      index_id: 8,
      name: 'Customer Category',
      type: 'link',
      icon: 'Customer Category',
      path: '/customer-category-list',
      main_menu_id: 14,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 42,
      index_id: 1,
      name: 'Staff',
      type: 'link',
      icon: 'Staff',
      path: '/staff-list',
      main_menu_id: 31,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 43,
      index_id: 2,
      name: 'Roles & Responsiblity',
      type: 'link',
      icon: 'Roles & Responsiblity',
      path: '/roles-list',
      main_menu_id: 31,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 44,
      index_id: 1,
      name: 'Staff',
      type: 'link',
      icon: 'Staff',
      path: '/staff-list',
      main_menu_id: 32,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 45,
      index_id: 2,
      name: 'Roles & Responsiblity',
      type: 'link',
      icon: 'Roles & Responsiblity',
      path: '/roles-list',
      main_menu_id: 32,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 46,
      index_id: 3,
      main_menu_id: 14,
      name: 'Items',
      type: 'dropdown',
      icon: 'itmes',
      path: '/item',
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment().toISOString(),
      updated_at: moment().toISOString(),
    },
    {
      id: 47,
      index_id: 3,
      main_menu_id: 35, // Ensure this exists in `Integrated_modules_main_menu`
      name: 'Products Approval',
      type: 'link',
      icon: 'Products Approval',
      path: '/product-approval-list',
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment().toISOString(),
      updated_at: moment().toISOString(),
    },
    {
      id: 48,
      index_id: 2,
      main_menu_id: 35, // Ensure this exists in `Integrated_modules_main_menu`
      name: 'Brand Approval',
      type: 'link',
      icon: 'Brand Approval',
      path: '/brand-approval-list',
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment().toISOString(),
      updated_at: moment().toISOString(),
    },
    {
      id: 49,
      index_id: 1,
      main_menu_id: 35, // Ensure this exists in `Integrated_modules_main_menu`
      name: 'Marketer Approval',
      type: 'link',
      icon: 'Marketer Approval',
      path: '/marketer-approval-list',
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment().toISOString(),
      updated_at: moment().toISOString(),
    },
    {
      id: 50,
      index_id: 5,
      main_menu_id: 14, // Ensure this exists in `Integrated_modules_main_menu`
      name: 'Logistic Area',
      type: 'link',
      icon: 'Logistic Area',
      path: '/logistic-area-list',
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment().toISOString(),
      updated_at: moment().toISOString(),
    },
    {
      id: 51,
      index_id: 1,
      main_menu_id: 21, // Ensure this exists in `Integrated_modules_main_menu`
      name: 'Customer Payments',
      type: 'link',
      icon: 'Customer Payments',
      path: '/customer-payments-list',
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment().toISOString(),
      updated_at: moment().toISOString(),
    },
    {
      id: 52,
      index_id: 2,
      main_menu_id: 21, // Ensure this exists in `Integrated_modules_main_menu`
      name: 'Vendor Payments',
      type: 'link',
      icon: 'Vendor Payments',
      path: '/vendor-payments-list',
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment().toISOString(),
      updated_at: moment().toISOString(),
    },
    {
      id: 53,
      index_id: 1,
      main_menu_id: 37, // Ensure this exists in `Integrated_modules_main_menu`
      name: 'Customer Activity',
      type: 'link',
      icon: 'Customer Activity',
      path: '/customer-activity-list',
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment().toISOString(),
      updated_at: moment().toISOString(),
    },
    {
      id: 54,
      index_id: 2,
      main_menu_id: 37, // Ensure this exists in `Integrated_modules_main_menu`
      name: 'Vendor Activity',
      type: 'link',
      icon: 'Vendor Activity',
      path: '/vendor-activity-list',
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment().toISOString(),
      updated_at: moment().toISOString(),
    },
  ];
  try {
    await knex.raw('TRUNCATE TABLE "Integrated_modules_sub_menu" RESTART IDENTITY CASCADE');
    console.log('Inserting Integrated_modules_sub_menu records...');
    await knex('Integrated_modules_sub_menu').insert(IntegratedModulesSubMenuRecords);
    await knex.raw(`
      SELECT SETVAL('public."Integrated_modules_sub_menu_id_seq"',
      COALESCE((SELECT MAX(id) FROM "Integrated_modules_sub_menu"), 1), true);
    `);
    console.log(' Integrated_modules_sub_menu seeding completed successfully!');
  } catch (error) {
    console.error(' Error seeding Integrated_modules_sub_menu table:', error);
  }
};