const moment = require('moment');
exports.seed = async function (knex) {
  console.log('Seeding Integrated_modules_main_menu table...');
  const IntegratedModulesRecords = [
    {
      id: 1,
      index_id: 1,
      name: 'Dashboard',
      type: 'link',
      icon: 'Dashboard',
      path: '/dashboard',
      menu_plan_id: 1,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 2,
      index_id: 2,
      name: 'Master',
      type: 'dropdown',
      icon: 'Master',
      path: '/master',
      menu_plan_id: 1,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 3,
      index_id: 4,
      name: 'Users',
      type: 'dropdown',
      icon: 'Users',
      path: '/users',
      menu_plan_id: 1,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 4,
      index_id: 11,
      name: 'Enquiry',
      type: 'dropdown',
      icon: 'Enquiry',
      path: '/enquiry',
      menu_plan_id: 1,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 5,
      index_id: 6,
      name: 'Customers',
      type: 'dropdown',
      icon: 'Customers',
      path: '/customers',
      menu_plan_id: 1,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 6,
      index_id: 7,
      name: 'Billing',
      type: 'dropdown',
      icon: 'Billing',
      path: '/billing',
      menu_plan_id: 1,
      active_status: 'inactive',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 7,
      index_id: 8,
      name: 'Payments',
      type: 'link',
      icon: 'Payments',
      path: '/payment',
      menu_plan_id: 1,
      active_status: 'inactive',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 8,
      index_id: 9,
      name: 'Comunity',
      type: 'link',
      icon: 'Comunity',
      path: '/comunity',
      menu_plan_id: 1,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 9,
      index_id: 10,
      name: 'Marketing',
      type: 'dropdown',
      icon: 'Marketing',
      path: '/marketing',
      menu_plan_id: 1,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 10,
      index_id: 12,
      name: 'Settings',
      type: 'dropdown',
      icon: 'Settings',
      path: '/settings',
      menu_plan_id: 1,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 11,
      index_id: 13,
      name: 'Staff',
      type: 'dropdown',
      icon: 'Staff',
      path: '/staff',
      menu_plan_id: 1,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 12,
      index_id: 14,
      name: 'Reports',
      type: 'dropdown',
      icon: 'Reports',
      path: '/reports',
      menu_plan_id: 1,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 13,
      index_id: 1,
      name: 'Dashboard',
      type: 'link',
      icon: 'Dashboard',
      path: '/dashboard',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 14,
      index_id: 2,
      name: 'Master',
      type: 'dropdown',
      icon: 'Master',
      path: '/master',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 15,
      index_id: 3,
      name: 'Items Price',
      type: 'link',
      icon: 'Items',
      path: '/item-price-list',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 16,
      index_id: 5,
      name: 'Custome Lead',
      type: 'link',
      icon: 'Lead',
      path: '/lead-list',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 17,
      index_id: 4,
      name: 'Vendor',
      type: 'link',
      icon: 'Vendor',
      path: '/vendor-list',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 18,
      index_id: 6,
      name: 'Customers',
      type: 'link',
      icon: 'Customers',
      path: '/customer-list',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 19,
      index_id: 8,
      name: 'Orders',
      type: 'dropdown',
      icon: 'Orders',
      path: '/orders',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 20,
      index_id: 9,
      name: 'Dispatched',
      type: 'link',
      icon: 'Dispatched',
      path: '/dispatched',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 21,
      index_id: 10,
      name: 'Payments',
      type: 'dropdown',
      icon: 'Payments',
      path: '/payment',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 22,
      index_id: 11,
      name: 'Discounts',
      type: 'link',
      icon: 'Discounts',
      path: '/discounts',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 37,
      index_id: 12,
      name: 'Activity',
      type: 'dropdown',
      icon: 'Activity',
      path: '/activity',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 23,
      index_id: 13,
      name: 'Comunity',
      type: 'dropdown',
      icon: 'Comunity',
      path: '/comunity',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 24,
      index_id: 14,
      name: 'Marketing',
      type: 'dropdown',
      icon: 'Marketing',
      path: '/marketing',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 25,
      index_id: 15,
      name: 'Settings',
      type: 'dropdown',
      icon: 'Settings',
      path: '/settings',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 26,
      index_id: 16,
      name: 'Staff',
      type: 'dropdown',
      icon: 'Staff',
      path: '/staff',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 27,
      index_id: 17,
      name: 'Reports',
      type: 'dropdown',
      icon: 'Reports',
      path: '/reports',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 28,
      index_id: 18,
      name: 'Upgrade',
      type: 'dropdown',
      icon: 'Upgrade',
      path: '/upgrade',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 29,
      index_id: 1,
      name: 'Dashboard',
      type: 'link',
      icon: 'Dashboard',
      path: '/dashboard',
      menu_plan_id: 34,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 30,
      index_id: 1,
      name: 'Dashboard',
      type: 'link',
      icon: 'Dashboard',
      path: '/dashboard',
      menu_plan_id: 35,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 31,
      index_id: 4,
      name: 'Staff',
      type: 'link',
      icon: 'staff',
      path: '/staff',
      menu_plan_id: 34,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 32,
      index_id: 4,
      name: 'Staff',
      type: 'link',
      icon: 'staff',
      path: '/staff',
      menu_plan_id: 35,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 33,
      index_id: 5,
      name: 'Reports',
      type: 'link',
      icon: 'Reports',
      path: '/reports',
      menu_plan_id: 34,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 34,
      index_id: 5,
      name: 'Reports',
      type: 'link',
      icon: 'Reports',
      path: '/reports',
      menu_plan_id: 35,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
    {
      id: 35,
      index_id: 3,
      name: 'Authorizations',
      type: 'dropdown',
      icon: 'Authorizations',
      path: '/authorizations',
      menu_plan_id: 1,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },

    {
      id: 36,
      index_id: 7,
      name: 'O-Form Issue',
      type: 'link',
      icon: 'OformIssue',
      path: '/oform-list',
      menu_plan_id: 2,
      active_status: 'active',
      actions: {
        "view": true,
        "add": true,
        "edit": true,
        "delete": true
      },
      created_at: moment(),
      updated_at: moment(),
    },
  ];
  try {
    await knex.raw('TRUNCATE TABLE "Integrated_modules_main_menu" RESTART IDENTITY CASCADE');
    console.log('Inserting Integrated_modules_main_menu records...');
    await knex('Integrated_modules_main_menu').insert(IntegratedModulesRecords);
    await knex.raw(`
      SELECT SETVAL('public."Integrated_modules_main_menu_id_seq"',
      COALESCE((SELECT MAX(id) FROM "Integrated_modules_main_menu"), 1), true);
    `);
    console.log('Integrated_modules_main_menu seeding completed successfully!');
  } catch (error) {
    console.error('Error seeding Integrated_modules_main_menu table:', error);
  }
};