const DemoMenuData = {
  success: true,
  menu: [
    {
      id: 94,
      name: "Dashboard",
      type: "link",
      icon: "Dashboard",
      path: "/dashboard",
      validity: true,
      page_status: true,
    },
    {
      id: 95,
      name: "Master",
      type: "dropdown",
      icon: "Master",
      validity: true,
      page_status: true,
      menu: [
        {
          id: 95,
          name: "Business",
          type: "dropdown",
          icon: "Master",
          validity: true,
          page_status: true,
          menu: [
            {
              id: 116,
              name: "Business Category",
              type: "link",
              path: "/business-category-list",
              validity: true,
              page_status: true,
            },
            {
              id: 116,
              name: "Business Sub Category",
              type: "link",
              path: "/business-sub-category-list",
              validity: true,
              page_status: true,
            },
          ],
        },

        {
          id: 116,
          name: "Supplier Type",
          type: "link",
          path: "/supplier-type-list",
          validity: true,
          page_status: true,
        },
        {
          id: 117,
          name: "Unit",
          type: "link",
          path: "/unit-list",
          validity: true,
          page_status: true,
        },
        {
          id: 118,
          name: "Brand",
          type: "link",
          path: "/brand-list",
          validity: true,
          page_status: true,
        },
        {
          id: 118,
          name: "GST",
          type: "link",
          path: "/gst-list",
          validity: true,
          page_status: true,
        },
        {
          id: 118,
          name: "Marketer",
          type: "link",
          path: "/marketer-list",
          validity: true,
          page_status: true,
        },
        {
          id: 95,
          name: "Product",
          type: "dropdown",
          icon: "Master",
          validity: true,
          page_status: true,
          menu: [
            {
              id: 119,
              name: "Product Class",
              type: "link",
              path: "/product-class-list",
              validity: true,
              page_status: true,
            },
            {
              id: 120,
              name: "Product Category",
              type: "link",
              path: "/product-category-list",
              validity: true,
              page_status: true,
            },
            {
              id: 120,
              name: "Product Sub Category",
              type: "link",
              path: "/product-sub-category-list",
              validity: true,
              page_status: true,
            },
            {
              id: 120,
              name: "Product",
              type: "link",
              path: "/product-list",
              validity: true,
              page_status: true,
            },
          ],
        },

        {
          id: 116,
          name: "Country",
          type: "link",
          path: "/country-list",
          validity: true,
          page_status: true,
        },
        {
          id: 116,
          name: "State",
          type: "link",
          path: "/state-list",
          validity: true,
          page_status: true,
        },
        {
          id: 116,
          name: "District",
          type: "link",
          path: "/district-list",
          validity: true,
          page_status: true,
        },
        {
          id: 116,
          name: "Tehsil",
          type: "link",
          path: "/tehsil-list",
          validity: true,
          page_status: true,
        },
        {
          id: 116,
          name: "Pin",
          type: "link",
          path: "/pin-list",
          validity: true,
          page_status: true,
        },
        {
          id: 116,
          name: "Place",
          type: "link",
          path: "/place-list",
          validity: true,
          page_status: true,
        },
      ],
    },

    {
      id: 95,
      name: "Users",
      type: "dropdown",
      icon: "Master",
      validity: true,
      page_status: true,
      menu: [
        {
          id: 116,
          name: "Business Entity",
          type: "link",
          path: "/business-entity-list",
          validity: true,
          page_status: true,
        },
        {
          id: 116,
          name: "NBFC",
          type: "link",
          path: "/nbfc-list",
          validity: true,
          page_status: true,
        },
      ],
    },
    {
      id: 95,
      name: "Marketing",
      type: "dropdown",
      icon: "Master",
      validity: true,
      page_status: true,
      menu: [
        {
          id: 116,
          name: "Text Sms",
          type: "link",
          path: "/text-sms-list",
          validity: true,
          page_status: true,
        },
        {
          id: 116,
          name: "WhatsApp",
          type: "link",
          path: "/whatsapp-list",
          validity: true,
          page_status: true,
        },
        {
          id: 116,
          name: "Email",
          type: "link",
          path: "/email-list",
          validity: true,
          page_status: true,
        },
        {
          id: 116,
          name: "Google Form",
          type: "link",
          path: "/google-form-list",
          validity: true,
          page_status: true,
        },
      ],
    },
  ],
  plan_name: "Perimum LMS 12 Month with 100 Studens",
};
export default DemoMenuData;
